master: add scripts

diff --git a/scripts/run-crypto b/scripts/run-crypto
--- a/scripts/run-crypto
+++ b/scripts/run-crypto
@@ -1,19 +1,17 @@
 #!/bin/sh
 
-conf_dir="conf"
 binary_dir="bin"
-# bitcoin_config="${HOME}/${conf_dir}/bitcoin.conf"
 bitcoin_dir="${HOME}/.bitcoin"
-# litecoin_config="${HOME}/${conf_dir}/litecoin.conf"
 litecoin_dir="${HOME}/.litecoin"
-litecoin_pid="${HOME}/${binary_dir}/litecoind.pid"
 btc_addr=modnSoevy3wuZoHCAEpqPjrXjjUb3qqwuw
 ltc_addr=mujyVMutzD9RWe67eSq49XLMpoMKNthR32
 wallet_path=${HOME}/.config/wallet/wallet.conf
 
+ERROR_CODE=-1
+
 sync_wallet () {
-    WALLET_PASSWORD=12345678 bitmark-wallet -C $wallet_path btc -t sync
-    WALLET_PASSWORD=12345678 bitmark-wallet -C $wallet_path ltc -t sync
+    WALLET_PASSWORD=12345678 bitmark-wallet -C "$wallet_path" btc -t sync
+    WALLET_PASSWORD=12345678 bitmark-wallet -C "$wallet_path" ltc -t sync
 }
 
 # teminate bitcoind
@@ -31,8 +29,8 @@ fi
 
 # copy config file if not exist
 if [ ! -f "${bitcoin_dir}/bitcoin.conf" ]; then
-    printf "copy bitcoin config into directory...\n"
-    cp "${bitcoin_config}" "${bitcoin_dir}"
+    printf "bitcoin config not exit...abort\n"
+    exit $ERROR_CODE
 fi
 
 # remove existing regtest data directory
@@ -68,8 +66,8 @@ fi
 
 # copy config file if not exist
 if [ ! -f "${litecoin_dir}/litecoin.conf" ]; then
-    printf "copy litecoin config into directory...\n"
-    cp "${litecoin_config}" "${litecoin_dir}"
+    printf "litecoin config not exit...abort\n"
+    exit $ERROR_CODE
 fi
 
 # remove existing regtest data directory
diff --git a/scripts/run-regression b/scripts/run-regression
--- a/scripts/run-regression
+++ b/scripts/run-regression
@@ -5,29 +5,24 @@ export PATH="${GOPATH}/bin":$PATH
 
 SUCCESS_CODE=0
 ERROR_CODE=1
+bitmarkd_cluster_numbers=("1" "2" "3" "4" "5")
+bitmarkd_connected=false
 
-start_time=""
-end_time=""
-
-# calculate time
-calculate_time() {
-    if [ "$start_time" == "" ]; then
-        start_time=$(date +%s)
-    elif [ "$end_time" == "" ]; then
-        end_time=$(date +%s)
-    else
-        printf "\n It takes %s seconds bitmarkd connect\n" "$(( $end_time - $start_time ))"
-    fi
+measure_time() {
+    s=$(date +%s)
+    "$@"
+    # rc=$?
+    printf "finish execution '%s' for %s seconds\n" "$@" $(($(date +%s) - s))
 }
 
 check_script_result() {
     if [ $# -ne 1 ]; then
-        printf "error argument, expect 1 but get $#"
+        printf "error argument, expect 1 but get %s" "$#"
         return $ERROR_CODE
     fi
 
     if [ $? -ne $SUCCESS_CODE ]; then
-        printf "execute $1 fail, abort...\n"
+        printf "execute %s fail, abort...\n" "$1"
         clean_up
         exit $ERROR_CODE
     fi
@@ -74,11 +69,10 @@ setup_bitmarkd () {
 }
 
 run_bitmarkd() {
-    array=("1" "2" "3" "4" "5")
-    for number in "${array[@]}"
+    for number in "${bitmarkd_cluster_numbers[@]}"
     do
         printf "\nStart bitmarkd %s" "${number}"
-        cd "${HOME}/.config/bitmarkd${number}"
+        cd "${HOME}/.config/bitmarkd${number}" || true
         nohup bitmarkd --config-file="bitmarkd${number}.conf" start >/dev/null 2>&1 &
 
         # wait for bitmarkd to initialize tcp, only for node number 3, 4
@@ -97,34 +91,28 @@ setup_recorderd() {
 }
 
 run_recorderd() {
-    # run recorderd
     printf "\nRun recorderd...\n"
     ~/bin/run-recorderd
 }
 
 check_bitmarkd() {
     # check connection, at leat 3 servers should be connected
-    found=false
-    for number in "${array[@]}"
+    for number in "${bitmarkd_cluster_numbers[@]}"
     do
         normal_mode=$(curl -s -k "https://localhost:2${number}31/bitmarkd/details" | jq | grep -c Normal)
         if [ "$normal_mode" != "$SUCCESS_CODE" ]; then
             printf "\nnode %s in Normal mode, cli port %s, https port %s\n" "${number}" "2${number}30" "2${number}31"
-	        found=true
+	        bitmarkd_connected=true
             break 1                 # break 1 levels of loop
         fi
     done
-
 }
 
 run_crypto
 check_crypto
 
-# start of time calculation: bitmarkd connect
-calculate_time
-
 setup_bitmarkd
-run_bitmarkd
+measure_time run_bitmarkd
 
 setup_recorderd
 check_script_result "setup-recorderd"
@@ -132,12 +120,11 @@ check_script_result "setup-recorderd"
 run_recorderd
 check_script_result "run-recorderd"
 
-# end of time calculation: bitmarkd connect
-calculate_time
+check_bitmarkd
 
-if [ "$found" = "false" ]; then
+if [ "$bitmarkd_connected" = "false" ]; then
     printf "bitmarkd cannot connected\n"
     exit $ERROR_CODE
 fi
 
-calculate_time
+exit $SUCCESS_CODE
