master: update scripts

diff --git a/scripts/run-regression b/scripts/run-regression
--- a/scripts/run-regression
+++ b/scripts/run-regression
@@ -3,6 +3,7 @@
 export GOPATH="${HOME}/gocode"
 export PATH="${GOPATH}/bin":$PATH
 
+SUCCESS_CODE=0
 ERROR_CODE=1
 
 # calculate time
@@ -12,14 +13,40 @@ calculate_time() {
     elif [ "$end_time" == "" ]; then
         end_time=$(date +%s)
     else
-        printf "\nIt takes %s seconds bitmarkd connect\n" "$(( $end_time - $start_time ))"
+        printf "\n It takes %s seconds bitmarkd connect\n" "$(( $end_time - $start_time ))"
     fi
+}
+
+check_script_result() {
+    if [ $# -ne 1 ]; then
+        printf "error argument, expect 1 but get $#"
+        exit $ERROR_CODE
+    fi
+
+    if [ $? -ne $SUCCESS_CODE ]; then
+        printf "execute $1 fail, abort..."
+        clean_up
+        exit $ERROR_CODE
+    fi
+}
+
+clean_up_programs=(
+    "bitmarkd"
+    "recorderd"
+    "bitcoind"
+    "litecoind"
+)
+
+clean_up() {
+    for program in "${clean_up_programs[@]}"
+    do
+        pkill -f "${program}"
+    done
 }
 
 # run crypto programs
 ~/bin/run-crypto
-
-# exit program if bitcoind or litecoind not exist
+check_script_result "run-crypto"
 
 # start of time calculation: bitmarkd connect
 start_time=""
@@ -31,16 +58,14 @@ for process in "${processes[@]}"
 do
     if ! pgrep "$process" &> /dev/null; then
         printf "\n%s is not started, abort...\n" "$process"
+        clean_up
         exit $ERROR_CODE
     fi
 done
 
 # setup bitmarkd if bitmarkd config not exist
 ~/bin/setup-bitmarkd
-if [ $? -ne 0 ]; then
-    printf "\nAbort..."
-    exit $ERROR_CODE
-fi
+check_script_result "setup-bitmarkd"
 
 # run bitmarkd
 array=("1" "2" "3" "4" "5")
@@ -51,20 +76,22 @@ do
     nohup bitmarkd --config-file="bitmarkd${number}.conf" start >/dev/null 2>&1 &
 
     # wait for bitmarkd to initialize tcp, only for node number 3, 4
-    if [ "$number" != "1" ] && [ "$number" != "5" ]; then
+    if [ "$number" == "3" ] || [ "$number" == "4" ]; then
         sleep 150
+    fi
+
+    if [ "$number" == "2" ]; then
+        sleep 230
     fi
 done
 
-printf "\nAll bitmarkds are started...\n"
-
-# setup recorderd if recorderd config not exist
-
 ~/bin/setup-recorderd
+check_script_result "setup-recorderd"
 
 # run recorderd
 printf "\nRun recorderd...\n"
 ~/bin/run-recorderd
+check_script_result "run-recorderd"
 
 # check connection, at leat 3 servers should be connected
 node_number=0
@@ -75,19 +102,9 @@ do
     if [ $normal_mode -ne 0 ]; then
         printf "\nnode ${number} in Normal mode, cli port 2${number}30, https port 2${number}31\n"
         node_number=$number
-        calculate_time
         break 1                 # break 1 levels of loop
     fi
 done
-printf "nodes are not connected...\n"
 
 # end of time calculation: bitmarkd connect
 calculate_time
-
-# update cli config, the existing port may not fit current staus
-# cd "${HOME}/conf"
-# cli_filename="cli.conf"
-# cli_port="2${node_number}30"
-# if [ -f "${cli_filename}" ]; then
-#     sed -i -- "s/\"connect\": \".*/\"connect\": \"127.0.0.1:${cli_port}\",/g" "${cli_filename}"
-# fi
